name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "backend"
          secrets: |
            DATABASE_URL
            JWT_SECRET
            RESEND_API
            BOT_TOKEN
            CASHFREE_CLIENT_SECRET
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RESEND_API: ${{ secrets.RESEND_API }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CASHFREE_LINK: ${{ env.CASHFREE_LINK }}
          CASHFREE_CLIENT_ID: ${{ env.CASHFREE_CLIENT_ID }}
          CASHFREE_CLIENT_SECRET: ${{ secrets.CASHFREE_CLIENT_SECRET }}